# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIllzXAdBUAr_HgPBiCp5l8xxmIb-5w4
"""

#Oratile Riet_46315713
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import pandas as pd

users_cluster1 = np.random.randint(100, 1000)
users_cluster2 = np.random.randint(100, 1000)
users_cluster3 = np.random.randint(100, 1000)

cluster1_steps = np.random.randint(8000, 12001, users_cluster1)
cluster1_sleep = np.random.uniform(7, 9, users_cluster1)

cluster2_steps = np.random.randint(5000, 8001, users_cluster2)
cluster2_sleep = np.random.uniform(6, 7.5, users_cluster2)

cluster3_steps = np.random.randint(2000, 5001, users_cluster3)
cluster3_sleep = np.random.uniform(5, 6.5, users_cluster3)

#array
steps = np.concatenate([cluster1_steps, cluster2_steps, cluster3_steps])
sleep = np.concatenate([cluster1_sleep, cluster2_sleep, cluster3_sleep])


data = pd.DataFrame({'Steps per Day': steps,     'Hours Slept per Night': sleep})
data.head()

"""Step2:Data Visualazation"""

#46315713_Oratile Riet
plt.figure(figsize=(8,6))
plt.scatter(data['Steps per Day'], data['Hours Slept per Night'], alpha=0.5)
plt.xlabel('Steps per Day')
plt.ylabel('Hours Slept per Night')
plt.title('Fitness Tracker Data Visualization')
plt.show()

"""Step3:Kmeans Clustering"""

#Oratile_Riet_46315713
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
data['Cluster'] = kmeans.fit_predict(data[['Steps per Day', 'Hours Slept per Night']])

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
data['Cluster'] = kmeans.fit_predict(data[['Steps per Day', 'Hours Slept per Night']])
data.head()

"""Step4:Cluster Visualization:

"""

#46315713_Oratile Riet
plt.figure(figsize=(8,6))
colors = ['red', 'green', 'blue']

for i in range(3):
    cluster_data = data[data['Cluster'] == i]
    plt.scatter(cluster_data['Steps per Day'], cluster_data['Hours Slept per Night'],
                label=f'Cluster {i+1}', alpha=0.5, color=colors[i])
    centers = kmeans.cluster_centers_
plt.scatter(centers[:,0], centers[:,1], c='black', marker='X', s=200, label='Centroids')

plt.xlabel('Steps per Day')
plt.ylabel('Hours Slept per Night')
plt.title('KMeans Clustering of Fitness Tracker Data')
plt.legend()
plt.show()

"""Step5:Cluster Analysis:

"""

#46315713_Oratile Riet
cluster_averages = data.groupby('Cluster').mean()
print("Cluster Averages:")
print(cluster_averages)